services:
  app:
    container_name: ssh-app
    build:
      context: .
      args:
        NPM_TOKEN: $NPM_TOKEN
    env_file:
      - .env
    ports:
      - "8081:3000"
    depends_on:
      - db

  db:
    container_name: ssh-database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}

volumes:
  db:
